version: '3.7'

services:
  nginx:
    image: nginx
    volumes:
      - media:/app/media
    depends_on:
      - web
    env_file: .env.dev
  db:
    image: postgres:12.0-alpine
    env_file: .env.dev
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

volumes:
  pgdata:
  media: