# Generated by Django 3.0 on 2019-12-15 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Наименование категории')),
                ('image', models.ImageField(height_field=400, upload_to='media/categories', width_field=400)),
            ],
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование заведения')),
                ('logo', models.ImageField(height_field=400, upload_to='media/logos', verbose_name='Логотип заведения', width_field=400)),
                ('image', models.ImageField(height_field=1000, upload_to='media/establishments', verbose_name='Фото заведения', width_field=1000)),
                ('popular', models.BooleanField(default=False, verbose_name='Популярное заведение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Наименование категории в меню заведения')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('OL', 'Оплата онлайн'), ('CS', 'Оплата наличными, при получении'), ('CA', 'Оплата картой, при получении')], max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Наименование товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена товара')),
                ('ingredients', models.TextField(blank=True, max_length=256, null=True)),
                ('popular', models.BooleanField(default=False, verbose_name='Популярный товар')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Establishment')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='products.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field=1000, upload_to='media/products', width_field=1000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='EstablishmentPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Establishment')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.PaymentType')),
            ],
            options={
                'unique_together': {('establishment', 'payment_type')},
            },
        ),
    ]
