# Generated by Django 3.0.2 on 2020-01-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200115_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='categories'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='image',
            field=models.ImageField(upload_to='establishments', verbose_name='Фото заведения'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='logo',
            field=models.ImageField(height_field=400, upload_to='logos', verbose_name='Логотип заведения', width_field=400),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(upload_to='products'),
        ),
    ]
