# Generated by Django 3.0.2 on 2020-01-18 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200116_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=40)),
                ('review_text', models.TextField()),
                ('phone', models.CharField(max_length=18)),
                ('rating', models.SmallIntegerField(max_length=1)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.Establishment')),
            ],
        ),
        migrations.CreateModel(
            name='EstablishmentKitchens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Establishment')),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Kitchen')),
            ],
            options={
                'unique_together': {('establishment', 'kitchen')},
            },
        ),
    ]
