# Generated by Django 3.0.2 on 2020-05-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200503_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promo',
            field=models.BooleanField(default=False, verbose_name='Акционный товар'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='category',
            field=models.ManyToManyField(to='products.Category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='kitchens',
            field=models.ManyToManyField(to='products.Kitchen', verbose_name='Кухни'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='payment',
            field=models.ManyToManyField(to='products.PaymentType', verbose_name='Способы оплаты'),
        ),
    ]
