# Generated by Django 3.0.2 on 2020-05-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200503_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/default.png', upload_to='products', verbose_name='Фото товара'),
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
